version: '3'
services:
  web:
    build: .
    command: 'nginx -p /feasyberries/ -c conf/nginx.conf'
    volumes:
      - '.:/feasyberries'
      - node_modules:/feasyberries/node_modules
    ports:
      - '8080:8080'
    working_dir: '/feasyberries'
  #   depends_on:
  #     - redis
  # redis:
  #   image: 'redis:alpine'
volumes:
  node_modules: