version: '3.9'
services:
  web:
    image: 'node:16.11-bullseye-slim'
    command: bash -c 'npm install && npm run dev -- --open --host'
    ports:
      - '3000:3000'
    working_dir: '/feasyberries'
    expose:
      - '3000'
    volumes:
      - '.:/feasyberries'
      - node_modules:/feasyberries/node_modules
    environment:
      - VITE_ENVIRONMENT=development
      - VITE_REDIS_URL=redis://redis:6379/0
    restart: on-failure
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - '6379:6379'
volumes:
  node_modules:
