version: '3'
services:
  web:
    build: .
    command: 'nginx -p /feasyberries/ -c conf/nginx.conf'
    volumes:
      - '.:/feasyberries'
      - node_modules:/feasyberries/node_modules
    ports:
      - '8080:8080'
      - '35729:35729'
    working_dir: '/feasyberries'
    environment:
      - REDIS_URL=redis
    depends_on:
      - redis
  svelte_builder:
    build: .
    command: bash -c "npm install && npm run dev"
    working_dir: '/feasyberries/src/svelte'
    volumes:
      - '.:/feasyberries'
      - 'svelte_node_modules:/feasyberries/src/svelte/node_modules'
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - '6379:6379'
volumes:
  node_modules:
  svelte_node_modules: