services:
  web:
    build: .
    command: bash -c 'pnpm install && pnpm run dev --host'
    ports:
      - 5173:5173
      - 3140:3140
      - 9315:9315
    working_dir: '/feasyberries'
    expose:
      - 5173
      - 3140
      - 9315
    volumes:
      - '.:/feasyberries'
      - node_modules:/feasyberries/node_modules
      - pnpm-store:/feasyberries/.pnpm-store
      - svelte-kit:/feasyberries/.svelte-kit
    environment:
      - VITE_ENVIRONMENT=development
volumes:
  node_modules:
  pnpm-store:
  svelte-kit:
